services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: reservations-development
    command: pnpm start:debug reservations
    ports:
      - '3000:3000' # Application port
      - '9229:9229' # Debugging port
    env_file:
      - ./apps/reservations/.env
    depends_on:
      - mongo

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      # target: development
    # command: pnpm start:dev auth
    ports:
      - '3001:3001'
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongo

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      # target: development
    # command: pnpm start:dev payments
    env_file:
      - ./apps/payments/.env

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      # target: development
    # command: pnpm start:dev notifications
    env_file:
      - ./apps/notifications/.env

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
