services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo

  reservations:
    image: nestjsregistry.azurecr.io/reservations/reservations:v2
    ports:
      - '3000:3000'
    env_file:
      - ../apps/reservations/.env
    depends_on:
      - mongo

  auth:
    image: nestjsregistry.azurecr.io/auth/auth:v2
    ports:
      - '3001:3001'
    env_file:
      - ../apps/auth/.env
    depends_on:
      - mongo

  payments:
    image: nestjsregistry.azurecr.io/payments/payments:v2
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'

  notifications:
    image: nestjsregistry.azurecr.io/notifications/notifications:v2
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3004:3004'

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
